background {
  blur_passes = 3
  blur_size = 8
  path = $HOME/Pictures/hyprlock.jpg
}

general {
  hide_cursor=true
}

input-field {
  size=200, 50
  outline_thickness = 2
  dots_size = 0.2
  dots_center=true
  dots_rounding = -1
  dots_spacing = 0.35
  outer_color = rgba(0, 0, 0, 0)
  inner_color = rgba(0, 0, 0, 0.2)
  font_color = rgba(220, 215, 186, 0.8)
  check_color = rgb(204, 136, 34)
  fail_color = rgba(204, 34, 34, 1.0)
  fail_text = KURWA WRONG
  placeholder_text=Hello, $USER
  fade_on_empty = false
  fade_timeout = 1000
  position=0, -80
  # shadow_passes=1
}

label {
  color=rgb(ebdbb2)
  font_family=JetBrains Mono
  font_size=70
  position=0, 300
  shadow_passes=1
  text = cmd[update:1000] echo "$(date +"%A, %B %d")"
}

image {
    path = $HOME/Pictures/ava.jpg
    size = 150
    border_size = 2
    rounding = 0
    position = 0, 70
    border_color = rgba(119, 152, 250, 1)
}
